/* eslint-disable @typescript-eslint/no-explicit-any */

import Link from '../SiteLink';
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Download, MapPin, Star, UsersRound } from 'lucide-react';
import { SafeImage } from '../SafeImage';


const roleLabels: Record<string,string> = { architect:'Kiến trúc sư',engineer:'Kỹ sư',interior_designer:'Thiết kế nội thất',contractor:'Nhà thầu',student:'Sinh viên',other:'Chuyên gia khác' };
const roles = [{value:'',label:'Tất cả'},{value:'architect',label:'Kiến trúc sư'},{value:'engineer',label:'Kỹ sư'},{value:'interior_designer',label:'Thiết kế nội thất'},{value:'contractor',label:'Nhà thầu'}];

export function CommunityView({people,stats,role,sort}:{people:{results:any[]};stats:any;role:string;sort:string}){
  return <main className="subpage discovery-page">
    <section className="discovery-hero community-hero"><div><p className="eyebrow">CỘNG ĐỒNG CHUYÊN MÔN</p><h1>Kết nối với KTS & kỹ sư</h1><p>Khám phá năng lực, hồ sơ đã duyệt và đánh giá xác thực của những người đang chia sẻ tài nguyên trên nền tảng.</p></div><dl><div><dt>{Number(stats?.members||0)}</dt><dd>Chuyên gia</dd></div><div><dt>{Number(stats?.products||0)}</dt><dd>Hồ sơ</dd></div><div><dt>{Number(stats?.downloads||0)}</dt><dd>Lượt tải</dd></div></dl></section>
    <nav className="community-filters" aria-label="Lọc cộng đồng">{roles.map(item=><Link className={role===item.value?'active':''} href={item.value?`/cong-dong?vai-tro=${item.value}`:'/cong-dong'} key={item.label}>{item.label}</Link>)}<span/><Link className={sort==='noi-bat'?'active':''} href={`/cong-dong${role?`?vai-tro=${role}&sap-xep=noi-bat`:'?sap-xep=noi-bat'}`}>Nổi bật</Link><Link className={sort==='moi'?'active':''} href={`/cong-dong${role?`?vai-tro=${role}&sap-xep=moi`:'?sap-xep=moi'}`}>Mới tham gia</Link></nav>
    <section className="community-directory"><div className="directory-heading"><div><UsersRound/><div><h2>{role?roleLabels[role]:'Thành viên cộng đồng'}</h2><p>{people.results.length} hồ sơ phù hợp.</p></div></div></div>{people.results.length?<div className="community-grid">{people.results.map(person=>{const avatar=person.avatar_key?`/api/profile-avatar/${person.user_id}?v=${encodeURIComponent(person.avatar_key)}`:person.account_image||'';return <article className="community-card" key={person.id}><div className="community-card-head">{avatar?<SafeImage src={avatar} alt={person.display_name}/>:<span>{String(person.display_name).split(' ').filter(Boolean).slice(-2).map((part:string)=>part[0]).join('').toUpperCase()}</span>}<div><h2>{person.display_name}{person.verification_status==='verified'&&<BadgeCheck aria-label="Đã xác minh"/>}</h2><p>{person.professional_title}</p></div></div><div className="community-meta"><span><BriefcaseBusiness/>{roleLabels[person.seller_type]||'Chuyên gia'}</span><span><MapPin/>{person.location||'Việt Nam'}</span></div>{person.bio&&<p className="community-bio">{person.bio}</p>}<dl><div><dt>{person.file_count}</dt><dd>Hồ sơ</dd></div><div><dt>{person.download_count}</dt><dd>Lượt tải</dd></div><div><dt>{person.review_count?Number(person.rating).toFixed(1):'—'}</dt><dd><Star/> {person.review_count?`${person.review_count} đánh giá`:'Chưa đánh giá'}</dd></div></dl><Link className="community-profile-link" href={`/kts/${person.slug}`}>Xem hồ sơ chuyên gia <ArrowRight/></Link></article>})}</div>:<div className="empty-state"><h2>Chưa có thành viên trong nhóm này</h2><p>Các hồ sơ mới sẽ xuất hiện sau khi người bán hoàn tất thông tin chuyên môn.</p></div>}</section>
    <section className="discovery-callout" id="yeu-cau-ban-ve"><UsersRound/><div><h2>Bạn cần một hồ sơ cụ thể?</h2><p>Tìm trong thư viện trước, hoặc tham gia với tư cách người bán để kết nối và chia sẻ chuyên môn cùng cộng đồng.</p></div><div className="callout-actions"><Link className="button" href="/tim-kiem">Tìm bản vẽ <Download/></Link><Link className="button button-primary" href="/dang-ban">Tham gia cộng đồng <ArrowRight/></Link></div></section>
  </main>;
}
