/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { MarketplaceHeader } from '../../../components/MarketplaceHeader';
import { PublicProductGrid } from '../../../components/PublicProductGrid';
import { getD1 } from '../../../db';
import { productSelect } from '../../../lib/marketplace';
export const dynamic='force-dynamic';const origin='https://nhadepchat.tranvukim-tvk.workers.dev';
async function seller(slug:string){return getD1().prepare(`SELECT up.slug,up.display_name,up.avatar_key,up.bio,up.location,sp.id,sp.seller_type,sp.professional_title,sp.company,sp.website,sp.verification_status,(SELECT COUNT(*) FROM products WHERE seller_id=sp.id AND status='approved') file_count,(SELECT COUNT(*) FROM downloads d JOIN products p ON p.id=d.product_id WHERE p.seller_id=sp.id) download_count FROM seller_profiles sp JOIN user_profiles up ON up.user_id=sp.user_id WHERE up.slug=?`).bind(slug).first<Record<string,any>>()}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params,s=await seller(slug);if(!s)return{title:'Không tìm thấy KTS',robots:{index:false,follow:false}};const description=`${s.professional_title} ${s.display_name}. ${s.file_count} hồ sơ đã duyệt trên Nhà Đẹp Chất.`;return{title:`${s.display_name} | Nhà Đẹp Chất`,description,alternates:{canonical:`${origin}/kts/${slug}`},openGraph:{title:s.display_name,description,url:`${origin}/kts/${slug}`,images:s.avatar_key?[`${origin}/api/profile-avatar/${slug}`]:[]}}}
export default async function SellerPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params,s=await seller(slug);if(!s)notFound();const rows=await getD1().prepare(`${productSelect()} WHERE p.seller_id=? AND p.status='approved' ORDER BY p.approved_at DESC LIMIT 50`).bind(s.id).all();return <><MarketplaceHeader/><main className="subpage"><section className="profile-hero"><div className="profile-avatar">{s.display_name.split(' ').slice(-2).map((x:string)=>x[0]).join('')}</div><div><p className="eyebrow">HỒ SƠ CHUYÊN GIA</p><h1>{s.display_name}{s.verification_status==='verified'&&<b>✓</b>}</h1><h2>{s.professional_title}</h2><p>{s.location||'Việt Nam'} · {s.seller_type}</p></div><dl><div><dt>{s.file_count}</dt><dd>Hồ sơ</dd></div><div><dt>{s.download_count}</dt><dd>Lượt tải</dd></div></dl></section><div className="profile-tabs"><b>Hồ sơ</b><span>Bộ sưu tập</span><span>Giới thiệu</span></div><section className="profile-about"><h2>Giới thiệu</h2><p>{s.bio||'Chưa cập nhật giới thiệu.'}</p></section><section><div className="section-heading"><h2>HỒ SƠ ĐÃ DUYỆT</h2></div><PublicProductGrid products={rows.results}/></section></main></>}
