'use client';

import { useMemo, useState } from 'react';

const categories = ['Biệt thự 1 tầng','Biệt thự 2 tầng','Biệt thự 3 tầng','Nhà cấp 4','Nhà phố','Nhà thờ','Nhà xưởng','Chung cư – Văn phòng','Trường học','Quy hoạch','Kết cấu','MEP','Biện pháp thi công','Mẫu dự toán','File tính kết cấu','Thuyết minh','Block CAD','SketchUp','Revit'];
const products = [
  { id: 1, title: 'Hồ sơ nhà phố 5x20m 2 tầng mái bằng', size: '5 × 20m', floors: '02 tầng', files: 'DWG · SKP · XLSX', views: 328, price: '49.000đ', image: 'https://static.kienviet.net/storage/uploads/2025/01/rio-house-nha-pho-huong-tay-voi-vuon-cay-xanh-mat-hava-studio_2.jpg' },
  { id: 2, title: 'Bản vẽ nhà phố 4x18m hiện đại có gara', size: '4 × 18m', floors: '03 tầng', files: 'DWG · PDF · SKP', views: 814, price: '69.000đ', image: 'https://static-6.happynest.vn/storage/uploads/2022/03/e9d52a32eac6c72e29b4208375ea2077.jpg' },
  { id: 3, title: 'Hồ sơ kiến trúc nhà mái Thái 1 tầng', size: '8 × 12m', floors: '01 tầng', files: 'DWG · PDF', views: 1290, price: 'MIỄN PHÍ', image: 'https://3adesign.vn/wp-content/uploads/mat-tien-nha-dep-anh-minh-long-thanh-3-3.jpg' },
  { id: 4, title: 'Nhà phố 5x16m mặt tiền lam gỗ', size: '5 × 16m', floors: '03 tầng', files: 'DWG · SKP · PDF', views: 506, price: '39.000đ', image: 'https://static.kienviet.net/storage/uploads/2024/06/kienviet-a2-house28-1718640013.jpg' },
  { id: 5, title: 'Thiết kế nhà phố xanh 4 tầng', size: '5 × 22m', floors: '04 tầng', files: 'DWG · SKP', views: 967, price: '79.000đ', image: 'https://static.kienviet.net/storage/uploads/2025/01/kienviet-top10-house-rio-house-kientruchava-1-1736927162.jpg' },
  { id: 6, title: 'Hồ sơ nhà phố có gara ô tô', size: '6 × 18m', floors: '03 tầng', files: 'DWG · XLSX · PDF', views: 742, price: '59.000đ', image: 'https://static-2.happynest.vn/storage/uploads/2022/11/nha-pho-co-gara-de-xe-21-1667295187.jpg' },
];

function Header({ onMenu }: { onMenu: () => void }) {
  return <><div className="topbar"><div className="wrap topbar-inner"><nav><a href="#">Trang chủ</a><a href="#new">Bản vẽ mới</a><a href="#free">Bản vẽ miễn phí</a><a href="#top">Top bản vẽ</a><a href="#">Dự toán</a><a href="#">Tài liệu xây dựng</a><a href="#">Hướng dẫn</a></nav></div></div><header className="site-header"><div className="wrap header-inner"><button className="mobile-menu" onClick={onMenu} aria-label="Mở danh mục">☰</button><a className="logo" href="#"><span className="logo-mark">BV</span><span><b>BẢN VẼ</b><strong>NHÀ ĐẸP</strong></span></a><form className="search" onSubmit={e=>e.preventDefault()}><input aria-label="Tìm kiếm" placeholder="Tìm nhà 5x20, nhà 2 tầng, file CAD..."/><button type="submit">TÌM KIẾM</button></form><div className="account"><a href="#">Tài khoản</a><a href="#">Đã tải</a><a className="cart" href="#">Giỏ hàng <b>0</b></a></div></div></header><div className="categorybar"><div className="wrap categorybar-inner"><button onClick={onMenu}>☰ &nbsp; DANH MỤC BẢN VẼ</button><nav><a href="#new">Bản vẽ mới</a><a href="#free">Miễn phí</a><a href="#top">Tải nhiều</a><a href="#">Hồ sơ đầy đủ</a><a href="#">Dự toán</a></nav><span>Hỗ trợ: 0904 873 388</span></div></div></>;
}
function LeftSidebar({ mobile, onClose }: { mobile?: boolean; onClose?: () => void }) {
  return <aside className={mobile ? 'left-sidebar drawer' : 'left-sidebar'}><div className="sidebar-title"><span>☰ DANH MỤC BẢN VẼ</span>{mobile && <button onClick={onClose}>×</button>}</div><ul>{categories.map((item,i)=><li key={item}><a href="#"><span>{['⌂','⌑','▦','◇'][i%4]}</span>{item}<b>›</b></a></li>)}</ul></aside>;
}
function ProductCard({ product, onOpen }: { product: typeof products[number]; onOpen: () => void }) {
  return <article className="product-card" onClick={onOpen} tabIndex={0} onKeyDown={e => (e.key==='Enter'||e.key===' ')&&onOpen()}><div className="product-image"><img src={product.image} alt={product.title} loading="lazy"/><span>HỒ SƠ ĐẦY ĐỦ</span></div><div className="product-body"><h3>{product.title}</h3><p className="meta">{product.size}<i/>{product.floors}</p><p className="files">{product.files}</p><div className="product-footer"><span>◉ {product.views.toLocaleString('vi-VN')} lượt xem</span><strong className={product.price==='MIỄN PHÍ'?'free':''}>{product.price}</strong></div></div></article>;
}
function RightSidebar(){return <aside className="right-sidebar"><section><h2>DANH MỤC</h2><div className="quick-cats">{categories.slice(0,10).map(x=><a key={x} href="#">Bản vẽ {x}</a>)}</div></section><section><h2 className="red">BẢN VẼ NỔI BẬT</h2>{products.slice(0,3).map(p=><a className="mini-product" key={p.id} href="#"><img src={p.image} alt="" loading="lazy"/><span>{p.title}<strong>{p.price}</strong></span></a>)}</section></aside>}
export default function Home(){const[drawer,setDrawer]=useState(false);const[sort,setSort]=useState('Mới nhất');const[selected,setSelected]=useState<(typeof products)[number]|null>(null);const sorted=useMemo(()=>sort==='Tải nhiều'?[...products].sort((a,b)=>b.views-a.views):products,[sort]);return <><Header onMenu={()=>setDrawer(true)}/>{drawer&&<><div className="drawer-backdrop" onClick={()=>setDrawer(false)}/><LeftSidebar mobile onClose={()=>setDrawer(false)}/></>}<main className="wrap page-grid"><LeftSidebar/><section className="catalog"><div className="breadcrumbs">Trang chủ / Danh mục / <b>Nhà phố</b></div><div className="catalog-head"><div><h1>BẢN VẼ NHÀ PHỐ</h1><p>Hiển thị 1–24 / 628 hồ sơ</p></div><label>Sắp xếp: <select value={sort} onChange={e=>setSort(e.target.value)}><option>Mới nhất</option><option>Tải nhiều</option><option>Giá thấp</option><option>Giá cao</option></select></label></div><div className="product-grid">{sorted.map(p=><ProductCard key={p.id} product={p} onOpen={()=>setSelected(p)}/>)}</div><nav className="pagination"><button>‹</button><button className="active">1</button><button>2</button><button>3</button><span>…</span><button>27</button><button>›</button></nav></section><RightSidebar/></main>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="detail-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={selected.title}/><div><small>BV-002841</small><h2>{selected.title}</h2><dl><dt>Kích thước</dt><dd>{selected.size}</dd><dt>Số tầng</dt><dd>{selected.floors}</dd><dt>Định dạng</dt><dd>{selected.files}</dd><dt>Dung lượng</dt><dd>84MB</dd></dl><p className="includes">✓ Kiến trúc &nbsp; ✓ Kết cấu &nbsp; ✓ Điện nước<br/>✓ SketchUp &nbsp; ✓ Dự toán</p><strong className="detail-price">{selected.price}</strong><button className="download">TẢI HỒ SƠ</button></div></article></div>}</>}
