/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- homepage adapter consumes the dynamic public D1 payload.
'use client';
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useMemo, useState } from 'react';
import { MarketplaceHeader } from '../components/MarketplaceHeader';
import { ProductCard as SharedProductCard } from '../components/ProductCard';

type Product = {id:string;slug:string;title:string;size:string;floors:string;files:string;views:number;price:string;image:string;type:string;architect:string;badge:string};
type Architect = {slug:string;name:string;files:number;downloads:string;photo?:string;verified:boolean};
const heroImage='https://static-6.happynest.vn/storage/uploads/2022/03/e9d52a32eac6c72e29b4208375ea2077.jpg';

const collections = [
  { name: 'NHÀ PHỐ 5M', count: 24, image: 'https://static.kienviet.net/storage/uploads/2025/01/rio-house-nha-pho-huong-tay-voi-vuon-cay-xanh-mat-hava-studio_2.jpg' },
  { name: 'BIỆT THỰ 2 TẦNG', count: 36, image: 'https://3adesign.vn/wp-content/uploads/mat-tien-nha-dep-anh-minh-long-thanh-3-3.jpg' },
  { name: 'NHÀ CẤP 4 ĐẸP', count: 18, image: 'https://static-2.happynest.vn/storage/uploads/2022/11/nha-pho-co-gara-de-xe-21-1667295187.jpg' },
  { name: 'NHÀ XƯỞNG TIÊU CHUẨN', count: 12, image: 'https://static.kienviet.net/storage/uploads/2024/06/kienviet-a2-house28-1718640013.jpg' },
  { name: 'FILE KẾT CẤU HAY', count: 42, image: 'https://static.kienviet.net/storage/uploads/2025/01/kienviet-top10-house-rio-house-kientruchava-1-1736927162.jpg' },
];

function Hero(){return <section className="hero-main"><div className="hero-copy"><p className="eyebrow">THƯ VIỆN HỒ SƠ XÂY DỰNG</p><h1>Tìm đúng hồ sơ<br/>bạn cần</h1><p className="hero-description">Kho bản vẽ kiến trúc, kết cấu, MEP, dự toán<br/>được chia sẻ bởi cộng đồng KTS & kỹ sư.</p><div className="hero-actions"><a className="primary-btn" href="#drawings">Tìm bản vẽ ngay</a><a className="secondary-btn" href="/tim-kiem?q=miễn phí">Bản vẽ miễn phí</a></div><div className="hero-stats"><span><b>43.000+</b>Hồ sơ bản vẽ</span><span><b>5.200+</b>Bản vẽ miễn phí</span><span><b>3.800+</b>KTS & kỹ sư</span><span><b>98.700+</b>Lượt tải</span></div></div><div className="hero-visual"><div className="blueprint-lines"/><img src={heroImage} alt="Kiến trúc nhà phố hiện đại"/><div className="blueprint-card"><small>HỒ SƠ ĐẦY ĐỦ</small><b>NHÀ PHỐ 5 × 20M</b><span>KT · KC · MEP · DT</span></div></div></section>}

function ArchitectPanel({architects}:{architects:Architect[]}){return <aside className="architect-panel" id="architects"><div className="panel-head"><h2>KTS NỔI BẬT</h2><a href="/tim-kiem">Xem tất cả →</a></div>{architects.length?architects.map(a=><a className="architect-row" href={`/kts/${a.slug}`} key={a.name}>{a.photo?<img src={a.photo} alt={a.name} loading="lazy"/>:<span className="architect-avatar">{a.name.split(' ').slice(-2).map(x=>x[0]).join('')}</span>}<div><h3>{a.name}{a.verified&&<b title="Đã xác minh">✓</b>}</h3><p>{a.files} hồ sơ <i/> {a.downloads} lượt tải</p></div></a>):<div className="panel-empty">Chưa có KTS nổi bật.</div>}</aside>}

function Drawings({products}:{products:Product[]}){const[sort,setSort]=useState('Mới nhất');const sorted=useMemo(()=>sort==='Tải nhiều'?[...products].sort((a,b)=>b.views-a.views):products,[sort,products]);return <section className="drawings" id="drawings"><div className="section-heading"><h2>BẢN VẼ MỚI</h2><div><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sắp xếp"><option>Mới nhất</option><option>Tải nhiều</option><option>Giá thấp</option><option>Giá cao</option></select><a href="/tim-kiem">Xem tất cả →</a></div></div>{sorted.length?<div className="product-grid">{sorted.slice(0,5).map(p=><SharedProductCard key={p.id} product={{...p,priceLabel:p.price,category:p.type,seller_name:p.architect}}/>)}</div>:<div className="empty-state"><h2>Chưa có bản vẽ đã duyệt</h2><p>Sản phẩm mới sẽ xuất hiện tại đây sau khi được quản trị viên duyệt.</p></div>}</section>}

function PopularPanel({products}:{products:Product[]}){return <aside className="popular-panel"><div className="panel-head"><h2>BẢN VẼ TẢI NHIỀU</h2><a href="/tim-kiem">Xem tất cả →</a></div>{products.length?products.slice(0,5).map(p=><a className="popular-row" href={`/ban-ve/${p.slug}`} key={p.id}>{p.image?<img src={p.image} alt="" loading="lazy"/>:<span className="image-placeholder"/>}<span><strong>{p.title}</strong><small>{p.size} · {p.floors}</small></span><b className={p.price==='MIỄN PHÍ'?'free-price':''}>{p.price}</b></a>):<div className="panel-empty">Chưa có dữ liệu lượt tải.</div>}</aside>}

function Collections(){return <section className="collections" id="collections"><div className="section-heading"><h2>BỘ SƯU TẬP NỔI BẬT</h2><a href="/tim-kiem">Xem tất cả →</a></div><div className="collection-grid">{collections.map(c=><a className="collection-card" href={`/tim-kiem?q=${encodeURIComponent(c.name)}`} key={c.name}><img src={c.image} alt={c.name} loading="lazy"/><span><strong>{c.name}</strong><small>{c.count} hồ sơ</small></span></a>)}</div></section>}

function Footer(){return <footer><div className="shell footer-inner"><a className="logo footer-logo" href="#"><span className="logo-mark"><i/></span><span><b>NHÀ ĐẸP CHẤT</b><small>MẪU NHÀ · BẢN VẼ · KTS</small></span></a><p>Nền tảng chia sẻ hồ sơ xây dựng từ cộng đồng kiến trúc sư và kỹ sư Việt Nam.</p><nav><a href="#drawings">Bản vẽ</a><a href="#collections">Bộ sưu tập</a><a href="#architects">Kiến trúc sư</a><a href="#sell">Đăng bán</a></nav></div></footer>}

export default function Home(){const[products,setProducts]=useState<Product[]>([]),[popular,setPopular]=useState<Product[]>([]),[architects,setArchitects]=useState<Architect[]>([]);useEffect(()=>{fetch('/api/public/home').then(r=>r.ok?r.json():Promise.reject()).then(data=>{const adapt=(p:any):Product=>({id:p.id,slug:p.slug,title:p.title,size:p.width&&p.length?`${p.width} × ${p.length}m`:'Chưa cập nhật',floors:p.floors?`${p.floors} tầng`:'—',files:p.formats||'',views:Number(p.download_count||0),price:p.is_free?'MIỄN PHÍ':`${Number(p.price).toLocaleString('vi-VN')}đ`,image:p.cover_id?`/api/assets/${p.cover_id}`:'',type:p.category,architect:p.seller_name,badge:p.is_free?'MIỄN PHÍ':'MỚI'});setProducts(data.products.map(adapt));setPopular(data.popular.map(adapt));setArchitects(data.architects.map((a:any)=>({slug:a.slug,name:a.display_name,files:Number(a.file_count||0),downloads:Number(a.download_count||0).toLocaleString('vi-VN'),verified:a.verification_status==='verified'})))}).catch(()=>{})},[]);return <><MarketplaceHeader/><main className="shell marketplace"><Hero/><ArchitectPanel architects={architects}/><Drawings products={products}/><PopularPanel products={popular}/><Collections/></main><Footer/></>}
