/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- Better Auth and fetch responses are narrowed at runtime.
'use client';

import { FormEvent, useState } from 'react';
import { authClient } from '../lib/auth-client';
import { useRouter } from 'next/navigation';

export function AccountPanel({name,email,role}:{name:string,email:string,role:string}){const router=useRouter(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function update(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const data=new FormData(e.currentTarget);const result=await authClient.updateUser({name:String(data.get('name'))});setBusy(false);setMessage(result.error?result.error.message||'Không thể cập nhật.':'Đã cập nhật tên hiển thị.');router.refresh()}async function avatar(file:File){setBusy(true);const form=new FormData();form.set('avatar',file);const response=await fetch('/api/marketplace/avatar',{method:'POST',body:form}),data=await response.json();setBusy(false);setMessage(response.ok?'Đã cập nhật ảnh đại diện.':data.error);router.refresh()}async function logout(){await authClient.signOut();router.push('/');router.refresh()}return <div className="account-grid"><section className="content-card"><h2>Thông tin tài khoản</h2><form className="auth-form compact" onSubmit={update}><label>Ảnh đại diện<input type="file" accept=".jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>e.target.files?.[0]&&avatar(e.target.files[0])}/><small>JPG, PNG hoặc WEBP, tối đa 5MB.</small></label><label>Tên hiển thị<input name="name" defaultValue={name} minLength={2}/></label><label>Email<input value={email} disabled/></label>{message&&<p className="form-success">{message}</p>}<button className="form-submit" disabled={busy}>Lưu thay đổi</button></form></section><aside className="content-card"><h2>Trạng thái</h2><p>Vai trò: <b>{role==='seller'?'Người bán':role==='admin'?'Quản trị viên':'Thành viên'}</b></p><a className="outline-action" href="/tai-khoan/da-luu">Bản vẽ đã lưu</a>{role==='user'?<a className="outline-action" href="/dang-ban">Tạo hồ sơ người bán</a>:<a className="outline-action" href="/dashboard">Mở dashboard</a>}<button className="text-action" onClick={logout}>Đăng xuất</button></aside></div>}
