/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';

import { ChangeEvent, DragEvent, FormEvent, KeyboardEvent, useEffect, useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Download, Eye, GripVertical, ImagePlus, Star, Trash2, UploadCloud, X } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { ProductGallery } from './ProductGallery';
import { RichTextEditor } from './RichTextEditor';

const steps=['Thông tin','Thông số','Hình ảnh','File hồ sơ','Giá & SEO','Xem trước'];
const buildings=['Nhà phố','Nhà cấp 4','Biệt thự','Nhà vườn','Nhà xưởng','Văn phòng','Trường học','Chung cư','Quy hoạch','Nội thất','Công trình khác'];
const styles=['Hiện đại','Tân cổ điển','Cổ điển','Mái Nhật','Mái Thái','Tối giản','Công nghiệp','Khác'];
const formats=['DWG','SKP','RVT','PDF','XLSX','DOCX','ZIP','RAR'];
const disciplines=['Kiến trúc','Kết cấu','Điện','Cấp thoát nước','MEP','PCCC','Nội thất','Phối cảnh','Dự toán','Thuyết minh','Tài liệu','Khác'];
const tools=['AutoCAD','SketchUp','Revit','3ds Max','Excel','ETABS','SAFE','SAP2000','Khác'];
type UploadItem={id:string;name:string;size:number;url?:string;progress:number;kind:'preview'|'file';type?:string;extension?:string;error?:boolean};
type FormDataShape={title:string;category:string;buildingType:string;style:string;shortDescription:string;description:string;width:string;length:string;floors:string;area:string;formats:string[];disciplines:string[];tools:string[];keywords:string[];isFree:boolean;price:string};
const initial:FormDataShape={title:'',category:'Nhà phố',buildingType:'Nhà phố',style:'Hiện đại',shortDescription:'',description:'',width:'',length:'',floors:'',area:'',formats:['DWG'],disciplines:['Kiến trúc'],tools:['AutoCAD'],keywords:[],isFree:true,price:'0'};

export function ProductWizard(){
  const params=useSearchParams(),editId=params.get('id');
  const [step,setStep]=useState(0),[data,setData]=useState(initial),[productId,setProductId]=useState<string|null>(editId),[uploads,setUploads]=useState<UploadItem[]>([]),[coverId,setCoverId]=useState<string|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[keywordInput,setKeywordInput]=useState('');
  useEffect(()=>{if(!editId)return;fetch(`/api/marketplace/products?id=${encodeURIComponent(editId)}`).then(r=>r.json()).then((p:any)=>{if(!p.id)return;const category=buildings.includes(p.category)?p.category:(buildings.includes(p.building_type)?p.building_type:'Công trình khác');setData({...initial,...p,category,buildingType:buildings.includes(p.building_type)?p.building_type:'Công trình khác',style:styles.includes(p.style)?p.style:'Khác',width:p.width||'',length:p.length||'',floors:p.floors||'',area:p.area||'',formats:String(p.formats||'').split(',').filter(Boolean),disciplines:p.disciplines||[],tools:p.tools||[],keywords:p.keywords||[],isFree:!!p.is_free,price:String(p.price||0),shortDescription:p.short_description||''});const assets=(p.assets||[]).map((a:any,i:number)=>({id:a.id,name:`Ảnh preview ${i+1}`,size:0,url:`/api/assets/${a.id}`,progress:100,kind:'preview' as const,type:a.type}));setUploads([...assets,...(p.files||[]).map((f:any)=>({id:f.id,name:f.name,size:f.size,extension:f.extension,progress:100,kind:'file' as const}))]);setCoverId(assets.find((a:UploadItem)=>a.type==='cover')?.id||assets[0]?.id||null)})},[editId]);
  const previews=uploads.filter(x=>x.kind==='preview'&&!x.error), sourceFiles=uploads.filter(x=>x.kind==='file');
  const suggestions=useMemo(()=>[data.buildingType,data.style,data.width&&data.length?`${data.width}x${data.length}m`:'',data.floors?`${data.floors} tầng`:'',...data.formats.map(x=>`file ${x.toLowerCase()}`),...data.disciplines].filter(Boolean).map(x=>String(x).toLowerCase()).filter((x,i,a)=>a.indexOf(x)===i&&!data.keywords.includes(x)).slice(0,8),[data]);
  function set(name:keyof FormDataShape,value:any){setData(prev=>({...prev,[name]:value}))}
  function toggle(name:'formats'|'disciplines'|'tools',value:string){set(name,data[name].includes(value)?data[name].filter(x=>x!==value):[...data[name],value])}
  function field(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>){set(e.target.name as keyof FormDataShape,e.target.value)}
  function plain(html:string){return html.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
  function validate(target=step){
    if(target===0){if(data.title.trim().length<12)return 'Tên hồ sơ cần ít nhất 12 ký tự.';if(data.shortDescription.trim().length<80||data.shortDescription.length>200)return 'Mô tả ngắn cần từ 80–200 ký tự.';if(plain(data.description).length<50)return 'Mô tả chi tiết cần ít nhất 50 ký tự.'}
    if(target===1&&(!data.formats.length||!data.disciplines.length||!data.tools.length))return 'Chọn ít nhất một định dạng, hạng mục và công cụ.';
    if(target===2&&!previews.length)return 'Cần ít nhất một ảnh preview.';
    if(target===3&&!sourceFiles.filter(x=>!x.error&&x.progress===100).length)return 'Cần ít nhất một file hồ sơ.';
    if(target===4){if(data.keywords.length<3||data.keywords.length>8)return 'Nhập từ 3 đến 8 từ khóa.';if(!data.isFree&&Number(data.price)<1000)return 'Giá bán tối thiểu là 1.000đ.'}
    return '';
  }
  async function saveDraft(){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/marketplace/products',{method:productId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,...(productId?{id:productId}:{}),width:data.width?Number(data.width):null,length:data.length?Number(data.length):null,floors:data.floors?Number(data.floors):null,area:data.area?Number(data.area):null,price:Number(data.price||0)})});const result:any=await response.json();if(!response.ok)throw new Error(result.error||'Không thể lưu bản nháp.');setProductId(result.id);setMessage('Đã lưu bản nháp.');return true}catch(e){setError(e instanceof Error?e.message:'Không thể lưu bản nháp.');return false}finally{setBusy(false)}}
  async function next(){const issue=validate();if(issue){setError(issue);return}if((step===0||step===1||step===4)&&!await saveDraft())return;setError('');setStep(Math.min(5,step+1))}
  async function uploadFiles(files:FileList|File[],kind:'preview'|'file'){
    if(!productId){setError('Hãy lưu thông tin sản phẩm trước khi upload.');return}
    for(const file of Array.from(files)){const temp=`temp-${crypto.randomUUID()}`;setUploads(v=>[...v,{id:temp,name:file.name,size:file.size,progress:0,kind}]);
      try{const pr=await fetch('/api/uploads/presign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,kind,name:file.name,mime:file.type||'application/octet-stream',size:file.size})});const presign:any=await pr.json();if(!pr.ok)throw new Error(presign.error);
        const result=await new Promise<any>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open(presign.direct?'PUT':'POST',presign.direct?presign.uploadUrl:'/api/uploads');if(presign.direct)Object.entries(presign.headers||{}).forEach(([k,v])=>xhr.setRequestHeader(k,String(v)));xhr.upload.onprogress=e=>e.lengthComputable&&setUploads(v=>v.map(x=>x.id===temp?{...x,progress:Math.round(e.loaded/e.total*100)}:x));xhr.onerror=()=>reject(new Error(`Không thể upload ${file.name}`));xhr.onload=async()=>{if(xhr.status<200||xhr.status>=300){reject(new Error(`Không thể upload ${file.name}`));return}if(!presign.direct){resolve(JSON.parse(xhr.responseText||'{}'));return}const done=await fetch('/api/uploads/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:presign.id,productId,objectKey:presign.objectKey,kind,originalName:presign.originalName,extension:file.name.split('.').pop()?.toLowerCase()||'',mime:presign.mime,size:file.size})});const json:any=await done.json();if(done.ok)resolve({...json,id:presign.id,url:kind==='preview'?`/api/assets/${presign.id}`:undefined});else reject(new Error(json.error))};const form=new FormData();form.set('productId',productId);form.set('kind',kind);form.set('file',file);xhr.send(presign.direct?file:form)});
        const extension=file.name.split('.').pop()?.toUpperCase()||'';setUploads(v=>v.map(x=>x.id===temp?{...x,id:result.id,url:result.url,extension,progress:100}:x));if(kind==='preview'&&!coverId)setCoverId(result.id);if(kind==='file'&&formats.includes(extension)&&!data.formats.includes(extension))set('formats',[...data.formats,extension]);
      }catch(e){setUploads(v=>v.map(x=>x.id===temp?{...x,error:true}:x));setError(e instanceof Error?e.message:'Upload thất bại.')}}
  }
  function drop(e:DragEvent<HTMLDivElement>,kind:'preview'|'file'){e.preventDefault();void uploadFiles(e.dataTransfer.files,kind)}
  async function remove(item:UploadItem){if(!item.id.startsWith('temp-'))await fetch('/api/marketplace/assets',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,kind:item.kind})});setUploads(v=>v.filter(x=>x.id!==item.id));if(coverId===item.id)setCoverId(null)}
  async function persistOrder(next:UploadItem[],newCover=coverId){if(!productId)return;setUploads([...next,...sourceFiles]);await fetch('/api/marketplace/assets',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,ids:next.map(x=>x.id),coverId:newCover||undefined})})}
  function reorder(from:string,to:string){if(from===to)return;const next=[...previews],a=next.findIndex(x=>x.id===from),b=next.findIndex(x=>x.id===to);if(a<0||b<0)return;const[m]=next.splice(a,1);next.splice(b,0,m);void persistOrder(next)}
  async function makeCover(id:string){setCoverId(id);await persistOrder(previews,id);setMessage('Đã chọn ảnh đại diện.')}
  function addKeyword(value=keywordInput){const key=value.trim().toLowerCase().replace(/^,+|,+$/g,'');if(key.length<2||data.keywords.includes(key)||data.keywords.length>=8)return;set('keywords',[...data.keywords,key]);setKeywordInput('')}
  function keywordKey(e:KeyboardEvent<HTMLInputElement>){if(e.key==='Enter'||e.key===','){e.preventDefault();addKeyword()}}
  async function submit(){for(let i=0;i<5;i++){const issue=validate(i);if(issue){setStep(i);setError(issue);return}}if(!productId||!await saveDraft())return;setBusy(true);const response=await fetch(`/api/marketplace/products/${productId}/submit`,{method:'POST'}),result:any=await response.json();setBusy(false);if(response.ok)setMessage('Sản phẩm đã được gửi duyệt.');else setError(result.error||'Không thể gửi duyệt.')}
  const areaSuggestion=data.width&&data.length?Math.round(Number(data.width)*Number(data.length)*100)/100:0;
  return <div className="wizard"><ol className="wizard-steps">{steps.map((name,i)=><li className={i===step?'active':i<step?'done':''} key={name}><span>{i<step?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{name}</li>)}</ol><form onSubmit={(e:FormEvent)=>{e.preventDefault();void next()}}><section className="wizard-panel">
    {step===0&&<div className="form-grid"><label className="wide">Tên hồ sơ <small>{data.title.length}/160 · Ví dụ: Hồ sơ nhà phố 5x20m hiện đại 3 tầng</small><input name="title" value={data.title} onChange={field} maxLength={160}/></label><label>Loại công trình<select name="category" value={data.category} onChange={e=>{field(e);set('buildingType',e.target.value)}}>{buildings.map(x=><option key={x}>{x}</option>)}</select></label><label>Phong cách<select name="style" value={data.style} onChange={field}>{styles.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Mô tả ngắn <small className={data.shortDescription.length>=80&&data.shortDescription.length<=200?'valid-count':''}>{data.shortDescription.length}/200 · Tối thiểu 80 ký tự</small><textarea name="shortDescription" value={data.shortDescription} onChange={field} maxLength={200} rows={3}/></label><label className="wide">Mô tả chi tiết <RichTextEditor value={data.description} onChange={v=>set('description',v)}/></label></div>}
    {step===1&&<><div className="form-grid"><label>Chiều rộng (m)<input name="width" type="number" step="0.1" value={data.width} onChange={field}/></label><label>Chiều dài (m)<input name="length" type="number" step="0.1" value={data.length} onChange={field}/></label><label>Số tầng<input name="floors" type="number" min="1" value={data.floors} onChange={field}/></label><label>Diện tích (m²)<input name="area" type="number" step="0.1" value={data.area} onChange={field}/>{areaSuggestion>0&&Number(data.area)!==areaSuggestion&&<button type="button" className="area-suggestion" onClick={()=>set('area',String(areaSuggestion))}>Dùng {areaSuggestion} m²</button>}</label></div><OptionGroup title="Hạng mục hồ sơ" values={disciplines} selected={data.disciplines} onToggle={v=>toggle('disciplines',v)}/><OptionGroup title="Công cụ sử dụng" values={tools} selected={data.tools} onToggle={v=>toggle('tools',v)}/><OptionGroup title="Định dạng bàn giao" values={formats} selected={data.formats} onToggle={v=>toggle('formats',v)}/></>}
    {step===2&&<UploadStep
      kind="preview" items={previews} coverId={coverId}
      onFiles={f=>uploadFiles(f,'preview')} onDrop={e=>drop(e,'preview')}
      onRemove={remove} onReorder={reorder} onCover={makeCover}
    />}
    {step===3&&<UploadStep
      kind="file" items={sourceFiles}
      onFiles={f=>uploadFiles(f,'file')} onDrop={e=>drop(e,'file')} onRemove={remove}
    />}
    {step===4&&<div className="seo-step"><div className="price-options"><label><input type="radio" checked={data.isFree} onChange={()=>set('isFree',true)}/> Miễn phí</label><label><input type="radio" checked={!data.isFree} onChange={()=>set('isFree',false)}/> Trả phí</label>{!data.isFree&&<label>Giá bán (VNĐ)<input name="price" type="number" min="1000" step="1000" value={data.price} onChange={field}/><small>Thanh toán chưa mở; giá chỉ hiển thị sau khi duyệt.</small></label>}</div><div className="keyword-editor"><h3>Từ khóa tìm kiếm <small>{data.keywords.length}/8 · cần 3–8 từ khóa</small></h3><div className="keyword-tags">{data.keywords.map(x=><span key={x}>{x}<button type="button" onClick={()=>set('keywords',data.keywords.filter(k=>k!==x))} aria-label={`Xóa ${x}`}><X/></button></span>)}</div><input value={keywordInput} onChange={e=>setKeywordInput(e.target.value)} onKeyDown={keywordKey} onBlur={()=>addKeyword()} placeholder="Nhập từ khóa rồi nhấn Enter"/><div className="keyword-suggestions"><small>Gợi ý:</small>{suggestions.map(x=><button type="button" key={x} onClick={()=>addKeyword(x)}>+ {x}</button>)}</div></div></div>}
    {step===5&&<div className="wizard-preview"><section><h2>Xem trước thẻ sản phẩm</h2><article className="product-card wizard-card"><div className="product-image">{previews[0]?<img src={(previews.find(x=>x.id===coverId)||previews[0]).url} alt=""/>:<div className="image-placeholder"/>}</div><div className="product-body"><h3>{data.title}</h3><p className="product-type">{data.category} · {data.style}</p><p className="product-meta">{data.width&&data.length?`${data.width} × ${data.length}m`:'Chưa cập nhật'} <i/> {data.floors?`${data.floors} tầng`:'—'}</p><div className="formats">{data.formats.map(x=><span key={x}>{x}</span>)}</div><div className="author"><span className="tiny-avatar">KTS</span><span>Hồ sơ của bạn</span><strong>{data.isFree?'MIỄN PHÍ':`${Number(data.price).toLocaleString('vi-VN')}đ`}</strong></div></div></article></section><section className="wizard-detail-preview"><h2>Xem trước trang chi tiết</h2><ProductGallery images={previews.map((x,i)=>({id:x.id,src:x.url!,alt:`${data.title} - ảnh ${i+1}`}))} compact/><h3>{data.title}</h3><p>{data.shortDescription}</p><div dangerouslySetInnerHTML={{__html:data.description}}/></section></div>}
    {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}
  </section><footer className="wizard-actions">{step>0&&<button type="button" className="outline-action" onClick={()=>{setError('');setStep(step-1)}}><ChevronLeft size={16}/>{step===5?'Quay lại chỉnh sửa':'Quay lại'}</button>}<button type="button" className="outline-action" disabled={busy} onClick={()=>void saveDraft()}>Lưu bản nháp</button>{step<5?<button className="form-submit" disabled={busy}>Tiếp tục<ChevronRight size={16}/></button>:<button type="button" className="form-submit" disabled={busy} onClick={()=>void submit()}>Gửi duyệt</button>}</footer></form></div>;
}

function OptionGroup({title,values,selected,onToggle}:{title:string;values:string[];selected:string[];onToggle:(v:string)=>void}){return <fieldset className="option-group"><legend>{title}</legend>{values.map(x=><label key={x}><input type="checkbox" checked={selected.includes(x)} onChange={()=>onToggle(x)}/>{x}</label>)}</fieldset>}
function UploadStep({kind,items,coverId,onFiles,onDrop,onRemove,onReorder,onCover}:{kind:'preview'|'file';items:UploadItem[];coverId?:string|null;onFiles:(f:FileList)=>void;onDrop:(e:DragEvent<HTMLDivElement>)=>void;onRemove:(i:UploadItem)=>void;onReorder?:(from:string,to:string)=>void;onCover?:(id:string)=>void}){return <><div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={onDrop}>{kind==='preview'?<ImagePlus/>:<UploadCloud/>}<b>{kind==='preview'?'Kéo thả ảnh preview':'Kéo thả file hồ sơ'}</b><span>{kind==='preview'?'JPG, PNG, WEBP · tối đa 30 ảnh, 10MB/ảnh':'DWG, SKP, RVT, PDF, XLSX, DOCX, ZIP, RAR · tối đa 250MB/file'}</span><label className="outline-action">Chọn file<input hidden type="file" multiple accept={kind==='preview'?'.jpg,.jpeg,.png,.webp':'.dwg,.skp,.rvt,.pdf,.xlsx,.docx,.zip,.rar'} onChange={e=>e.target.files&&onFiles(e.target.files)}/></label></div><div className="upload-list">{items.map((item,index)=><article className={`${item.error?'upload-error':''}${coverId===item.id?' is-cover':''}`} key={item.id} draggable={kind==='preview'} onDragStart={e=>e.dataTransfer.setData('text/plain',item.id)} onDragOver={e=>kind==='preview'&&e.preventDefault()} onDrop={e=>{if(kind==='preview'){e.preventDefault();onReorder?.(e.dataTransfer.getData('text/plain'),item.id)}}}>{kind==='preview'?<GripVertical size={16}/>:<span className="file-order">{index+1}</span>}{item.url?<img src={item.url} alt=""/>:<span className="file-extension">{item.extension||item.name.split('.').pop()?.toUpperCase()}</span>}<span><b>{item.name}</b><small>{item.error?'Upload thất bại':item.progress<100?`Đang tải ${item.progress}%`:item.size?`${(item.size/1024/1024).toFixed(2)} MB`:'Đã tải lên'}</small><i><em style={{width:`${item.progress}%`}}/></i></span><div className="upload-actions">{kind==='preview'&&<><a href={item.url} target="_blank" rel="noreferrer" aria-label="Xem ảnh"><Eye/></a><button type="button" className="cover-action" onClick={()=>onCover?.(item.id)} aria-label="Làm ảnh bìa"><Star fill={coverId===item.id?'currentColor':'none'}/><span>{coverId===item.id?'Ảnh bìa':'Đặt bìa'}</span></button></>}{kind==='file'&&!item.id.startsWith('temp-')&&<a href={`/api/download/${item.id}`} aria-label="Tải file"><Download/></a>}<button type="button" onClick={()=>onRemove(item)} aria-label="Xóa"><Trash2/></button></div></article>)}</div></>}
