/* eslint-disable @typescript-eslint/no-explicit-any */
import { FavoriteButton } from './FavoriteButton';

export type ProductCardData=Record<string,any>;
export function ProductCard({product:p,preview=false}:{product:ProductCardData;preview?:boolean}){
  const image=p.image||(p.cover_id?`/api/assets/${p.cover_id}`:''),isFree=Boolean(p.is_free)||p.priceLabel==='MIỄN PHÍ',formats=Array.isArray(p.formats)?p.formats:String(p.formats||p.files||'').split(/[·,]/).map((x:string)=>x.trim()).filter(Boolean),seller=p.seller_name||p.architect||'Nhà Đẹp Chất';
  const dimensions=p.size||(p.width&&p.length?`${p.width} × ${p.length}m`:'Chưa cập nhật'),floors=typeof p.floors==='string'?p.floors:p.floors?`${p.floors} tầng`:'—',price=p.priceLabel||(isFree?'MIỄN PHÍ':`${Number(p.price||0).toLocaleString('vi-VN')}đ`);
  return <article className="product-card"><a className="product-card-link" href={preview?undefined:`/ban-ve/${p.slug}`}><div className="product-image">{image?<img src={image} alt={p.title} loading="lazy"/>:<div className="image-placeholder"/>}<b className={isFree?'card-badge free':'card-badge'}>{isFree?'MIỄN PHÍ':'MỚI'}</b></div><div className="product-body"><h3>{p.title}</h3><p className="product-type">{p.category||p.type}</p><p className="product-meta">{dimensions}<i/>{floors}</p>{formats.length>0&&<div className="formats">{formats.map((format:string)=><span key={format}>{format}</span>)}</div>}<div className="author"><span className="tiny-avatar">{seller.split(' ').filter(Boolean).slice(-2).map((x:string)=>x[0]).join('').toUpperCase()}</span><span>{seller}{p.verification_status==='verified'&&<b>✓</b>}</span><strong className={isFree?'free-price':''}>{price}</strong></div></div></a>{!preview&&p.id&&<FavoriteButton productId={p.id} returnUrl={`/ban-ve/${p.slug}`}/>}</article>;
}
